#!/usr/bin/env bash
# shellcheck source=/dev/null disable=
#
# script for querying wolfram-alpha api from command line
#


# if WOLFRAM_APP_ID is empty & ~/.config/wac/config is readable
if [[ -z "$WOLFRAM_APP_ID" && -r "$HOME"/.config/wac/config ]]; then
  source "$HOME"/.config/wac/config
fi

function usage() {
  printf "
Usage:
  %s [OPTIONS] <your query>

  Options:
  -h    show this help
  -s    spoken mode (default)
  -r    result mode
  -w    query the web interface
  " "$0"
}

function main() {

  app_id=$WOLFRAM_APP_ID
  mode="spoken"
  base_url="https://api.wolframalpha.com/v1"
  query="$*"

  OPTIND=1 # OPTIND is not automatically reset

  while getopts "hsrw" OPTNAME; do
    case "$OPTNAME" in
    h)
      usage
      exit 0
      ;;
    s)
      mode="spoken"
      shift
      ;;
    r)
      mode="result"
      shift
      ;;
    w)
      shift
      explorer.exe "https://www.wolframalpha.com/input?i=$*"
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
    esac
  done

  curl --data "appid=$app_id" --data-urlencode "i=$*" "$base_url/$mode"
}
main "$@"
